# Generated by Django 5.0.4 on 2026-05-19 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('notes', 'Notes'), ('video', 'Video'), ('pdf', 'PDF'), ('slides', 'Slides'), ('link', 'External Link'), ('other', 'Other')], default='pdf', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('external_link', models.URLField(blank=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='classes.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='subjects.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='teachers.teacher')),
            ],
            options={
                'db_table': 'study_materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
