# Generated by Django 5.0.4 on 2026-05-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=10)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('max_students', models.PositiveIntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'classes',
                'ordering': ['name', 'section'],
            },
        ),
    ]
